### ISSUE TITLE
[1.21] Affinity's EMI recipes (Aspen Infusion and Spirit Assimilation) make use of a missing class

### ISSUE THREAD

**Issue by unilock** [wisp-forest/affinity#27]
The EMI compatibility for Aspen Infusion and Spirit Assimilation recipes make use of `me.shedaniel.math.Point`, which isn't native to any of Affinity's required dependencies (I believe it's from either Cloth Config or REI), leading to a rendering error when whichever mod includes it is not installed.

<details>
<summary>Aspen Infusion</summary>

```
[16:47:59] [Render thread/INFO]: [STDERR]: java.lang.NoClassDefFoundError: me/shedaniel/math/Point
[16:47:59] [Render thread/INFO]: [STDERR]: 	at io.wispforest.affinity.compat.emi.recipe.AspenInfusionEmiRecipe.addWidgets(AspenInfusionEmiRecipe.java:58)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at dev.emi.emi.screen.RecipeDisplay.getWidgets(RecipeDisplay.java:73)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at dev.emi.emi.screen.RecipeTab.constructWidgets(RecipeTab.java:40)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at dev.emi.emi.screen.RecipeScreen.setPage(RecipeScreen.java:381)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at dev.emi.emi.screen.RecipeScreen.lambda$new$3(RecipeScreen.java:72)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_4185.method_25306(class_4185.java:96)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_4264.method_25348(class_4264.java:48)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_339.method_25402(class_339.java:141)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_4069.method_25402(class_4069.java:38)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at dev.emi.emi.screen.RecipeScreen.method_25402(RecipeScreen.java:454)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_312.method_1611(class_312.java:107)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:431)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_312.method_1601(class_312.java:107)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_312.method_22686(class_312.java:196)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:108)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_312.method_22684(class_312.java:196)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:184)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1310)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:882)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:256)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
[16:47:59] [Render thread/INFO]: [STDERR]: Caused by: java.lang.ClassNotFoundException: me.shedaniel.math.Point
[16:47:59] [Render thread/INFO]: [STDERR]: 	... 29 more
```
</details>

<details>
<summary>Spirit Assimilation</summary>

```
[16:47:59] [Render thread/INFO]: [STDERR]: java.lang.NoClassDefFoundError: me/shedaniel/math/Point
[16:47:59] [Render thread/INFO]: [STDERR]: 	at io.wispforest.affinity.compat.emi.recipe.SpiritAssimilationEmiRecipe.addWidgets(SpiritAssimilationEmiRecipe.java:57)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at dev.emi.emi.screen.RecipeDisplay.getWidgets(RecipeDisplay.java:73)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at dev.emi.emi.screen.RecipeTab.constructWidgets(RecipeTab.java:40)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at dev.emi.emi.screen.RecipeScreen.setPage(RecipeScreen.java:381)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at dev.emi.emi.screen.RecipeScreen.focusCategory(RecipeScreen.java:344)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at dev.emi.emi.screen.RecipeScreen.method_25402(RecipeScreen.java:451)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_312.method_1611(class_312.java:107)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:431)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_312.method_1601(class_312.java:107)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_312.method_22686(class_312.java:196)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:108)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_312.method_22684(class_312.java:196)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:184)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1310)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:882)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:256)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
[16:47:59] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
[16:47:59] [Render thread/INFO]: [STDERR]: Caused by: java.lang.ClassNotFoundException: me.shedaniel.math.Point
[16:47:59] [Render thread/INFO]: [STDERR]: 	... 25 more
```
</details>

**Comment by gliscowo** [comment]
The fix for this is now available in the [0.1.4 release](https://modrinth.com/mod/affinity/version/0.1.4+1.21)
Thanks for reporting!
