### ISSUE TITLE
Client crash when hovering over "brown potion" in EMI

### ISSUE THREAD

**Issue by joakibj** [wisp-forest/affinity#30]
When hovering over the "brown potion" in EMI, the client crashes.

Minecraft version: 1.21.1
Affinity version: 0.1.7

**Screenshot**
The potion to right of the Milk Cup
![brown_potion_cropped](https://github.com/user-attachments/assets/16d5bbd3-3e4f-4018-8867-b9daad3cc36b)

**Crash stacktrace**
```
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2024-12-16 21:08:47
Description: Rendering screen

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1842.method_8049()" because the return value of "net.minecraft.class_6880.comp_349()" is null
	at knot//net.minecraft.class_1844.method_57402(class_1844.java:89)
	at knot//io.wispforest.affinity.misc.potion.PotionUtil.getPotionEffects(PotionUtil.java:33)
	at knot//io.wispforest.affinity.statuseffects.BanishedStatusEffect.lambda$static$1(BanishedStatusEffect.java:35)
	at knot//net.fabricmc.fabric.api.client.item.v1.ItemTooltipCallback.lambda$static$0(ItemTooltipCallback.java:35)
	at knot//net.minecraft.class_1799.handler$zpl001$fabric-item-api-v1$getTooltip(class_1799.java:4136)
	at knot//net.minecraft.class_1799.method_7950(class_1799.java:807)
	at knot//net.minecraft.class_437.method_25408(class_437.java:243)
	at knot//dev.emi.emi.screen.FakeScreen.getTooltipComponentListFromItem(FakeScreen.java:26)
	at knot//dev.emi.emi.platform.fabric.EmiAgnosFabric.getItemTooltipAgnos(EmiAgnosFabric.java:196)
	at knot//dev.emi.emi.platform.EmiAgnos.getItemTooltip(EmiAgnos.java:102)
	at knot//dev.emi.emi.api.stack.ItemEmiStack.getTooltip(ItemEmiStack.java:175)
	at knot//dev.emi.emi.screen.EmiScreenManager.renderCurrentTooltip(EmiScreenManager.java:755)
	at knot//dev.emi.emi.screen.EmiScreenManager.drawForeground(EmiScreenManager.java:661)
	at knot//net.minecraft.class_465.handler$zkh000$emi$renderForeground(class_465.java:3239)
	at knot//net.minecraft.class_465.method_25394(class_465.java:127)
	at knot//net.minecraft.class_485.method_25394(class_485.java:32)
	at knot//net.minecraft.class_490.method_25394(class_490.java:81)
	at knot//net.minecraft.class_437.method_47413(class_437.java:117)
	at knot//net.minecraft.class_757.mixinextras$bridge$method_47413$179(class_757.java)
	at knot//net.minecraft.class_757.wrapOperation$bhl000$fabric-screen-api-v1$onRenderScreen(class_757.java:2086)
	at knot//net.minecraft.class_757.method_3192(class_757.java:913)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1285)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Mod list**
```
Mods:
  [✔️] accessories_tclayer-3.10.0-beta.18+1.21.1.jar
  [✔️] accessories-fabric-1.1.0-beta.16+1.21.1.jar
  [✔️] affinity-0.1.7+1.21.1.jar
  [✔️] cardinal-components-api-6.1.1.jar
  [✔️] emi-1.1.18+1.21.1+fabric.jar
  [✔️] fabric-api-0.110.0+1.21.1.jar
  [✔️] lavender-0.1.14+1.21.jar
  [✔️] owo-lib-0.12.15+1.21.jar
  [✔️] TerraBlender-fabric-1.21.1-4.1.0.5.jar
```

**Comment by gliscowo** [comment]
Are you certain that the modlist you provided is in fact the modlist at the time you encountered this crash? Using the exact same arrangement, I cannot reproduce the crash.

Further, as always, I ask you to supply the complete `latest.log` from the time the crash happened - it contains tons of potentially useful information
